sonar.organization=miguelzod24
sonar.projectKey=MiguelZod24_Bank_Project
sonar.projectName=Bank_Project

sonar.sources=.
sonar.inclusions=tests/**/*.py,pages/**/*.py,scripts/**/*.py,conftest.py
sonar.exclusions=reports/**,allure-results/**,**/__pycache__/**,**/*.pyc

sonar.python.version=3.11
