name: QA Automation Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Todos los días a las 6:00 AM UTC = 8:00 AM España
    - cron: '0 6 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Paso 1 — descarga el código
      - name: Checkout del código
        uses: actions/checkout@v4

      # Paso 2 — instala Python 3.11
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Paso 3 — instala Java (necesario para Allure)
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Paso 4 — instala Allure CLI
      - name: Instalar Allure
        run: |
          wget -q https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      # Paso 5 — instala las dependencias de Python
      - name: Instalar dependencias
        run: |
          pip install pytest
          pip install playwright
          pip install pytest-playwright
          pip install faker
          pip install pytest-html
          pip install allure-pytest

      # Paso 6 — instala los navegadores de Playwright
      - name: Instalar navegadores Playwright
        run: playwright install --with-deps chromium

       # Paso 7 — ejecuta los tests con Allure y pytest-html
      - name: Ejecutar tests
        run: pytest tests/ -v --html=reports/report.html --self-contained-html --alluredir=reports/allure-results

      # Paso 8 — genera el reporte Allure
      - name: Generar reporte Allure
        if: always()
        run: allure generate reports/allure-results -o reports/allure-report --clean

      # Paso 9 — guarda ambos reportes como artefactos descargables
      - name: Guardar reportes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reportes-tests
          path: reports/